# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2c4928ff780f72763bf501c250c2980d054ed771a75d1cda128f8bd683327aaca6865d372e7572bfadf95adf22bd3b24ada3bb67c4e379e886d4a27f96dd7840

test:
  secret_key_base: 687f157b151a2ab34c37f2758bd34758ff6f907de0490018f44bde23c901bb5a81a1d8455a603b27180aaa3967152b7c7b64486588689e933fc5f2ec6afe49e0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
